/**
 * MM Interiors — Centralized SEO Metadata System
 * Source of truth: AntiGravity Master Implementation + SEO Map
 * 
 * Every indexable page has unique: title, description, canonical, OG data.
 * Canonical URLs use HTTPS and match the final preferred URL exactly.
 */

const SITE_URL = 'https://mminterior.in';
const SITE_NAME = 'MM Interiors';
const DEFAULT_OG_IMAGE = '/images/home/mm-interiors-hyderabad-og.jpg';

export const seoData = {
  '/': {
    title: 'Interior Designers in Hyderabad | MM Interiors',
    description: 'MM Interiors — trusted home interior designers in Hyderabad. Complete home interiors including modular kitchens, wardrobes, living rooms, bedrooms, false ceilings and more. Get a free consultation.',
    h1: 'Home Interior Designers in Hyderabad',
    canonical: `${SITE_URL}/`,
    noindex: false,
  },
  '/about': {
    title: 'About MM Interiors | Home Interior Designers in Hyderabad',
    description: 'Learn about MM Interiors — our design philosophy, team, experience and approach to creating beautiful homes in Hyderabad.',
    h1: 'About MM Interiors',
    canonical: `${SITE_URL}/about`,
    noindex: false,
  },
  '/services': {
    title: 'Interior Design Services in Hyderabad | MM Interiors',
    description: 'Explore our complete range of interior design services in Hyderabad — from modular kitchens and wardrobes to false ceilings, wall finishes and full home interiors.',
    h1: 'Interior Design Services in Hyderabad',
    canonical: `${SITE_URL}/services`,
    noindex: false,
  },
  '/home-interiors-hyderabad': {
    title: 'Home Interiors in Hyderabad | Full Home Interior Design',
    description: 'Complete home interior design in Hyderabad by MM Interiors. We design and execute every room — kitchen, wardrobes, living, bedrooms, ceilings and more — as one coordinated home.',
    h1: 'Full Home Interior Design in Hyderabad',
    canonical: `${SITE_URL}/home-interiors-hyderabad`,
    noindex: false,
  },
  '/modular-kitchen-design-hyderabad': {
    title: 'Modular Kitchen Design in Hyderabad | MM Interiors',
    description: 'Custom modular kitchen design in Hyderabad. L-shaped, U-shaped, parallel and straight layouts with quality shutters, hardware, countertops and smart storage solutions.',
    h1: 'Modular Kitchen Designers in Hyderabad',
    canonical: `${SITE_URL}/modular-kitchen-design-hyderabad`,
    noindex: false,
  },
  '/wardrobe-design-hyderabad': {
    title: 'Wardrobe Design in Hyderabad | Custom & Modular Wardrobes',
    description: 'Custom and modular wardrobe design in Hyderabad. Sliding, hinged and loft wardrobes with smart internal organization, quality finishes and hardware.',
    h1: 'Wardrobe Designers in Hyderabad',
    canonical: `${SITE_URL}/wardrobe-design-hyderabad`,
    noindex: false,
  },
  '/living-room-interiors-hyderabad': {
    title: 'Living Room Interior Designers in Hyderabad | MM Interiors',
    description: 'Living room interior design in Hyderabad. TV walls, seating layouts, storage, false ceilings, lighting and partition designs that connect your living, dining and foyer areas.',
    h1: 'Living Room Interior Design in Hyderabad',
    canonical: `${SITE_URL}/living-room-interiors-hyderabad`,
    noindex: false,
  },
  '/master-bedroom-interiors-hyderabad': {
    title: 'Master Bedroom Interiors in Hyderabad | MM Interiors',
    description: 'Master bedroom interior design in Hyderabad. Bed wall design, wardrobes, vanity, lighting, ceiling and storage solutions for a comfortable, personal retreat.',
    h1: 'Master Bedroom Interior Design in Hyderabad',
    canonical: `${SITE_URL}/master-bedroom-interiors-hyderabad`,
    noindex: false,
  },
  '/bedroom-interiors-hyderabad': {
    title: 'Bedroom Interior Designers in Hyderabad | MM Interiors',
    description: 'Bedroom interior design in Hyderabad. Master, guest and additional bedroom designs with wardrobes, storage, lighting and furniture solutions.',
    h1: 'Bedroom Interior Design in Hyderabad',
    canonical: `${SITE_URL}/bedroom-interiors-hyderabad`,
    noindex: false,
  },
  '/kids-room-interiors-hyderabad': {
    title: 'Kids Room Interior Designers in Hyderabad | MM Interiors',
    description: 'Kids room interior design in Hyderabad. Safe, durable and creative spaces with study areas, smart storage, flexible furniture and designs that grow with your child.',
    h1: 'Kids Room Interior Design in Hyderabad',
    canonical: `${SITE_URL}/kids-room-interiors-hyderabad`,
    noindex: false,
  },
  '/pooja-room-interiors-hyderabad': {
    title: 'Pooja Room Design in Hyderabad | MM Interiors',
    description: 'Pooja room interior design in Hyderabad. Compact pooja units, dedicated pooja rooms, jaali work, storage, lighting and material options for modern and traditional homes.',
    h1: 'Pooja Room Interior Design in Hyderabad',
    canonical: `${SITE_URL}/pooja-room-interiors-hyderabad`,
    noindex: false,
  },
  '/dining-room-interiors-hyderabad': {
    title: 'Dining Room Interiors in Hyderabad | MM Interiors',
    description: 'Dining room interior design in Hyderabad. Dining table zones, crockery units, lighting, wall treatments and designs that connect with your kitchen and living room.',
    h1: 'Dining Room Interior Design in Hyderabad',
    canonical: `${SITE_URL}/dining-room-interiors-hyderabad`,
    noindex: false,
  },
  '/bathroom-interiors-hyderabad': {
    title: 'Bathroom Interiors in Hyderabad | MM Interiors',
    description: 'Bathroom interior design in Hyderabad. Vanity units, storage solutions, tile selection, lighting and fixture planning for functional, beautiful bathrooms.',
    h1: 'Bathroom Interior Design in Hyderabad',
    canonical: `${SITE_URL}/bathroom-interiors-hyderabad`,
    noindex: false,
  },
  '/home-office-interiors-hyderabad': {
    title: 'Home Office & Study Room Interiors in Hyderabad | MM Interiors',
    description: 'Home office and study room interior design in Hyderabad. Ergonomic desks, smart storage, lighting, cable management and quiet workspace solutions.',
    h1: 'Home Office Interior Design in Hyderabad',
    canonical: `${SITE_URL}/home-office-interiors-hyderabad`,
    noindex: false,
  },
  '/foyer-design-hyderabad': {
    title: 'Foyer & Entrance Interior Design in Hyderabad | MM Interiors',
    description: 'Foyer and entrance design in Hyderabad. Shoe storage, console tables, mirrors, lighting and partition solutions that create a strong first impression.',
    h1: 'Foyer Design in Hyderabad',
    canonical: `${SITE_URL}/foyer-design-hyderabad`,
    noindex: false,
  },
  '/balcony-interiors-hyderabad': {
    title: 'Balcony Interior Design in Hyderabad | MM Interiors',
    description: 'Balcony interior design in Hyderabad. Seating, storage, planters, flooring and privacy solutions for apartment balconies.',
    h1: 'Balcony Interior Design in Hyderabad',
    canonical: `${SITE_URL}/balcony-interiors-hyderabad`,
    noindex: false,
  },
  '/staircase-interiors-hyderabad': {
    title: 'Staircase & Staircase Wall Design in Hyderabad | MM Interiors',
    description: 'Staircase interior design in Hyderabad. Wall paneling, lighting, railing finishes, under-stair storage and artwork for villas, duplexes and independent houses.',
    h1: 'Staircase Interior Design in Hyderabad',
    canonical: `${SITE_URL}/staircase-interiors-hyderabad`,
    noindex: false,
  },
  '/false-ceiling-design-hyderabad': {
    title: 'False Ceiling & Lighting Design in Hyderabad | MM Interiors',
    description: 'False ceiling design in Hyderabad. Living room, bedroom, dining, kitchen ceilings with integrated lighting, AC integration and maintenance guidance.',
    h1: 'False Ceiling Designers in Hyderabad',
    canonical: `${SITE_URL}/false-ceiling-design-hyderabad`,
    noindex: false,
  },
  '/interior-lighting-design-hyderabad': {
    title: 'Interior Lighting Design in Hyderabad | MM Interiors',
    description: 'Interior lighting design in Hyderabad. Ambient, task, accent and concealed lighting solutions that enhance the mood and function of every room.',
    h1: 'Interior Lighting Design in Hyderabad',
    canonical: `${SITE_URL}/interior-lighting-design-hyderabad`,
    noindex: false,
  },
  '/tv-unit-design-hyderabad': {
    title: 'TV Unit & Entertainment Wall Design in Hyderabad | MM Interiors',
    description: 'TV unit and entertainment wall design in Hyderabad. Storage, wall paneling, lighting, cable management and complete wall compositions for your living room.',
    h1: 'TV Unit Design in Hyderabad',
    canonical: `${SITE_URL}/tv-unit-design-hyderabad`,
    noindex: false,
  },
  '/wall-paneling-design-hyderabad': {
    title: 'Wall Panelling & Feature Wall Design in Hyderabad | MM Interiors',
    description: 'Wall panelling and feature wall design in Hyderabad. Fluted panels, wood-look finishes, textured surfaces and stone-look options with real material guidance.',
    h1: 'Wall Panelling Design in Hyderabad',
    canonical: `${SITE_URL}/wall-paneling-design-hyderabad`,
    noindex: false,
  },
  '/wallpaper-design-installation-hyderabad': {
    title: 'Wallpaper Design & Installation in Hyderabad | MM Interiors',
    description: 'Wallpaper design and installation in Hyderabad. Room applications, feature walls, surface preparation, installation and maintenance guidance.',
    h1: 'Wallpaper Installation in Hyderabad',
    canonical: `${SITE_URL}/wallpaper-design-installation-hyderabad`,
    noindex: false,
  },
  '/3d-wall-panels-hyderabad': {
    title: '3D Wall Panels in Hyderabad | MM Interiors',
    description: '3D wall panel design in Hyderabad. Patterns, applications, lighting integration, installation and maintenance for textured wall finishes.',
    h1: '3D Wall Panel Design in Hyderabad',
    canonical: `${SITE_URL}/3d-wall-panels-hyderabad`,
    noindex: false,
  },
  '/wall-painting-interiors-hyderabad': {
    title: 'Interior Wall Painting & Wall Finishes in Hyderabad | MM Interiors',
    description: 'Interior wall painting and wall finishes in Hyderabad. Paint selections, textures, accent walls, color planning and surface preparation guidance.',
    h1: 'Interior Wall Finishes in Hyderabad',
    canonical: `${SITE_URL}/wall-painting-interiors-hyderabad`,
    noindex: false,
  },
  '/flooring-interiors-hyderabad': {
    title: 'Home Flooring Solutions in Hyderabad | MM Interiors',
    description: 'Home flooring solutions in Hyderabad. Options, transitions, maintenance guidance and integration with your overall interior design.',
    h1: 'Flooring Solutions for Home Interiors',
    canonical: `${SITE_URL}/flooring-interiors-hyderabad`,
    noindex: false,
  },
  '/curtains-blinds-hyderabad': {
    title: 'Curtains & Blinds for Home Interiors in Hyderabad | MM Interiors',
    description: 'Curtains and blinds in Hyderabad. Window treatments, fabric selection, measurements and installation as part of your home interior design.',
    h1: 'Curtains & Blinds in Hyderabad',
    canonical: `${SITE_URL}/curtains-blinds-hyderabad`,
    noindex: false,
  },
  '/custom-furniture-hyderabad': {
    title: 'Custom Furniture for Home Interiors in Hyderabad | MM Interiors',
    description: 'Custom furniture design in Hyderabad. Made-to-measure sofas, beds, consoles, dining tables and storage that integrate with your home interior.',
    h1: 'Custom Furniture Design in Hyderabad',
    canonical: `${SITE_URL}/custom-furniture-hyderabad`,
    noindex: false,
  },
  '/interior-electrical-work-hyderabad': {
    title: 'Interior Electrical & Switch Planning in Hyderabad | MM Interiors',
    description: 'Interior electrical planning in Hyderabad. Switch locations, lighting points, concealed wiring and TV/data point coordination for your home interior project.',
    h1: 'Interior Electrical Planning in Hyderabad',
    canonical: `${SITE_URL}/interior-electrical-work-hyderabad`,
    noindex: false,
  },
  '/interior-plumbing-work-hyderabad': {
    title: 'Interior Plumbing Coordination in Hyderabad | MM Interiors',
    description: 'Interior plumbing coordination in Hyderabad. Kitchen and bathroom plumbing scope, waterproofing and coordination with your interior project.',
    h1: 'Interior Plumbing Work in Hyderabad',
    canonical: `${SITE_URL}/interior-plumbing-work-hyderabad`,
    noindex: false,
  },
  '/home-renovation-hyderabad': {
    title: 'Home Renovation & Remodeling in Hyderabad | MM Interiors',
    description: 'Home renovation in Hyderabad. Kitchen, bathroom and room renovation with before/after transformations, process guidance and cost factors.',
    h1: 'Home Renovation in Hyderabad',
    canonical: `${SITE_URL}/home-renovation-hyderabad`,
    noindex: false,
  },
  '/2bhk-interior-design-hyderabad': {
    title: '2BHK Interior Design in Hyderabad | MM Interiors',
    description: '2BHK interior design in Hyderabad. Complete living, kitchen, bedroom, wardrobe, TV unit, ceiling and lighting design for your 2BHK home.',
    h1: '2BHK Interior Design in Hyderabad',
    canonical: `${SITE_URL}/2bhk-interior-design-hyderabad`,
    noindex: false,
  },
  '/3bhk-interior-design-hyderabad': {
    title: '3BHK Interior Design in Hyderabad | MM Interiors',
    description: '3BHK interior design in Hyderabad. Living, dining, kitchen, three bedrooms, wardrobes, pooja room, TV unit and ceiling design for your 3BHK home.',
    h1: '3BHK Interior Design in Hyderabad',
    canonical: `${SITE_URL}/3bhk-interior-design-hyderabad`,
    noindex: false,
  },
  '/4bhk-villa-interiors-hyderabad': {
    title: '4BHK & Villa Interior Designers in Hyderabad | MM Interiors',
    description: '4BHK and villa interior design in Hyderabad. Large space planning, multiple bedrooms, dining, pooja, staircase and custom furniture for premium homes.',
    h1: '4BHK & Villa Interior Design in Hyderabad',
    canonical: `${SITE_URL}/4bhk-villa-interiors-hyderabad`,
    noindex: false,
  },
  '/apartment-interiors-hyderabad': {
    title: 'Apartment Interior Designers in Hyderabad | MM Interiors',
    description: 'Apartment interior design in Hyderabad. Space-efficient solutions for compact storage, rooms and coordinated execution within apartment constraints.',
    h1: 'Apartment Interior Design in Hyderabad',
    canonical: `${SITE_URL}/apartment-interiors-hyderabad`,
    noindex: false,
  },
  '/villa-interiors-hyderabad': {
    title: 'Villa Interior Designers in Hyderabad | MM Interiors',
    description: 'Villa interior design in Hyderabad. Large spaces, staircases, double-height areas, custom furniture, lighting and multiple room design for villas.',
    h1: 'Villa Interior Design in Hyderabad',
    canonical: `${SITE_URL}/villa-interiors-hyderabad`,
    noindex: false,
  },
  '/duplex-interiors-hyderabad': {
    title: 'Duplex Interior Designers in Hyderabad | MM Interiors',
    description: 'Duplex interior design in Hyderabad. Vertical circulation, staircase design, double-height spaces, room zoning and lighting solutions.',
    h1: 'Duplex Interior Design in Hyderabad',
    canonical: `${SITE_URL}/duplex-interiors-hyderabad`,
    noindex: false,
  },
  '/modern-interiors-hyderabad': {
    title: 'Modern Home Interior Design in Hyderabad | MM Interiors',
    description: 'Modern home interior design in Hyderabad. Clean lines, smart storage, minimal aesthetics, quality materials and real project examples.',
    h1: 'Modern Home Interior Design in Hyderabad',
    canonical: `${SITE_URL}/modern-interiors-hyderabad`,
    noindex: false,
  },
  '/contemporary-interiors-hyderabad': {
    title: 'Contemporary Home Interior Design in Hyderabad | MM Interiors',
    description: 'Contemporary home interior design in Hyderabad. Current yet timeless forms, materials, lighting and storage solutions through real project work.',
    h1: 'Contemporary Home Interiors in Hyderabad',
    canonical: `${SITE_URL}/contemporary-interiors-hyderabad`,
    noindex: false,
  },
  '/minimalist-interiors-hyderabad': {
    title: 'Minimalist Interior Design in Hyderabad | MM Interiors',
    description: 'Minimalist home interiors in Hyderabad. Neutral palettes, hidden storage, clean geometry, thoughtful lighting and projects that prove less is more.',
    h1: 'Minimalist Home Interiors in Hyderabad',
    canonical: `${SITE_URL}/minimalist-interiors-hyderabad`,
    noindex: false,
  },
  '/traditional-interiors-hyderabad': {
    title: 'Traditional Indian Interior Design in Hyderabad | MM Interiors',
    description: 'Traditional Indian home interiors in Hyderabad. Wood, jaali, pooja, brass accents and classic design details through real project examples.',
    h1: 'Traditional Indian Home Interiors in Hyderabad',
    canonical: `${SITE_URL}/traditional-interiors-hyderabad`,
    noindex: false,
  },
  '/affordable-home-interiors-hyderabad': {
    title: 'Affordable Home Interiors in Hyderabad | MM Interiors',
    description: 'Affordable home interiors in Hyderabad. Scope control, material choices, budget priorities and transparent cost guidance for value-focused homeowners.',
    h1: 'Affordable Home Interiors in Hyderabad',
    canonical: `${SITE_URL}/affordable-home-interiors-hyderabad`,
    noindex: false,
  },
  '/luxury-home-interiors-hyderabad': {
    title: 'Luxury Home Interiors in Hyderabad | MM Interiors',
    description: 'Luxury home interior design in Hyderabad. Premium materials, custom detailing, sophisticated lighting, bespoke furniture and larger home projects.',
    h1: 'Luxury Home Interior Design in Hyderabad',
    canonical: `${SITE_URL}/luxury-home-interiors-hyderabad`,
    noindex: false,
  },
  '/interior-design-cost-hyderabad': {
    title: 'Interior Design Cost in Hyderabad | MM Interiors',
    description: 'Interior design cost in Hyderabad. Understand what affects your budget — BHK size, room scope, materials, hardware, civil work, timeline and more.',
    h1: 'Interior Design Cost in Hyderabad',
    canonical: `${SITE_URL}/interior-design-cost-hyderabad`,
    noindex: false,
  },
  '/2bhk-interior-design-cost-hyderabad': {
    title: '2BHK Interior Design Cost in Hyderabad | MM Interiors',
    description: '2BHK interior design cost in Hyderabad. Scope breakdown for kitchen, wardrobes, rooms, ceiling and lighting to help you plan your budget.',
    h1: '2BHK Interior Design Cost in Hyderabad',
    canonical: `${SITE_URL}/2bhk-interior-design-cost-hyderabad`,
    noindex: false,
  },
  '/3bhk-interior-design-cost-hyderabad': {
    title: '3BHK Interior Design Cost in Hyderabad | MM Interiors',
    description: '3BHK interior design cost in Hyderabad. Room-by-room scope breakdown, material choices and optional items to help you plan your 3BHK project budget.',
    h1: '3BHK Interior Design Cost in Hyderabad',
    canonical: `${SITE_URL}/3bhk-interior-design-cost-hyderabad`,
    noindex: false,
  },
  '/interior-design-process-hyderabad': {
    title: 'Interior Design Process | MM Interiors Hyderabad',
    description: 'How the interior design process works at MM Interiors Hyderabad. From consultation and site visit through design, materials, execution, quality checks and handover.',
    h1: 'Interior Design Process in Hyderabad',
    canonical: `${SITE_URL}/interior-design-process-hyderabad`,
    noindex: false,
  },
  '/interior-materials-hyderabad': {
    title: 'Home Interior Materials Guide | MM Interiors Hyderabad',
    description: 'Interior materials guide by MM Interiors. Plywood, laminates, hardware, countertops, wall finishes — how to choose, durability and maintenance.',
    h1: 'Interior Materials Guide',
    canonical: `${SITE_URL}/interior-materials-hyderabad`,
    noindex: false,
  },
  '/quality-warranty-hyderabad': {
    title: 'Interior Quality, Materials & Warranty | MM Interiors Hyderabad',
    description: 'Interior quality and warranty at MM Interiors. Workmanship standards, material checks, inspection process and warranty terms.',
    h1: 'Interior Quality & Warranty',
    canonical: `${SITE_URL}/quality-warranty-hyderabad`,
    noindex: false,
  },
  '/interior-design-projects': {
    title: 'Interior Design Projects in Hyderabad | MM Interiors',
    description: 'View completed interior design projects by MM Interiors in Hyderabad. Real homes, real transformations — kitchens, living rooms, bedrooms and complete homes.',
    h1: 'Interior Design Projects in Hyderabad',
    canonical: `${SITE_URL}/interior-design-projects`,
    noindex: false,
  },
  '/gallery': {
    title: 'Interior Design Gallery | MM Interiors Hyderabad',
    description: 'Browse the MM Interiors design gallery. Real project photography across kitchens, living rooms, bedrooms, wardrobes, ceilings and complete homes in Hyderabad.',
    h1: 'Interior Design Gallery Hyderabad',
    canonical: `${SITE_URL}/gallery`,
    noindex: false,
  },
  '/before-after-interiors-hyderabad': {
    title: 'Before & After Home Interior Transformations | MM Interiors',
    description: 'See real before and after interior transformations by MM Interiors. Genuine home makeovers with project details and transformation stories.',
    h1: 'Interior Before & After Transformations',
    canonical: `${SITE_URL}/before-after-interiors-hyderabad`,
    noindex: false,
  },
  '/interior-design-reviews-hyderabad': {
    title: 'MM Interiors Customer Reviews | Hyderabad Interior Projects',
    description: 'Read genuine customer reviews of MM Interiors Hyderabad. Real feedback from homeowners about their interior design experience.',
    h1: 'MM Interiors Reviews',
    canonical: `${SITE_URL}/interior-design-reviews-hyderabad`,
    noindex: false,
  },
  '/interior-design-faq-hyderabad': {
    title: 'Interior Design FAQs | Hyderabad Home Interiors',
    description: 'Frequently asked questions about interior design in Hyderabad. Cost, timeline, materials, design changes, site visits, execution and warranty.',
    h1: 'Interior Design FAQs',
    canonical: `${SITE_URL}/interior-design-faq-hyderabad`,
    noindex: false,
  },
  '/interior-design-inspiration-hyderabad': {
    title: 'Home Interior Design Inspiration | Hyderabad | MM Interiors',
    description: 'Interior design inspiration by MM Interiors. Room ideas, design styles, material guides and real project stories from Hyderabad homes.',
    h1: 'Interior Design Inspiration',
    canonical: `${SITE_URL}/interior-design-inspiration-hyderabad`,
    noindex: false,
  },
  '/blog': {
    title: 'Interior Design Blog | MM Interiors Hyderabad',
    description: 'Interior design blog by MM Interiors Hyderabad. Cost guides, design guides, project stories, material guides and helpful advice for homeowners.',
    h1: 'Interior Design Blog Hyderabad',
    canonical: `${SITE_URL}/blog`,
    noindex: false,
  },
  '/contact': {
    title: 'Contact MM Interiors | Interior Designers in Hyderabad',
    description: 'Contact MM Interiors in Hyderabad. Call, WhatsApp or fill out the form for a free interior design consultation.',
    h1: 'Contact MM Interiors in Hyderabad',
    canonical: `${SITE_URL}/contact`,
    noindex: false,
  },
  '/get-free-quote': {
    title: 'Get a Free Interior Design Consultation | MM Interiors Hyderabad',
    description: 'Request a free interior design consultation from MM Interiors Hyderabad. Share your requirements and get expert guidance for your home project.',
    h1: 'Get a Free Interior Design Quote',
    canonical: `${SITE_URL}/get-free-quote`,
    noindex: false,
  },
  '/privacy-policy': {
    title: 'Privacy Policy | MM Interiors',
    description: 'Privacy policy for MM Interiors website. How we handle your personal information and contact data.',
    h1: 'Privacy Policy',
    canonical: `${SITE_URL}/privacy-policy`,
    noindex: false,
  },
  '/terms-and-conditions': {
    title: 'Terms and Conditions | MM Interiors',
    description: 'Terms and conditions for MM Interiors services and website usage.',
    h1: 'Terms and Conditions',
    canonical: `${SITE_URL}/terms-and-conditions`,
    noindex: false,
  },
  '/refund-cancellation': {
    title: 'Refund & Cancellation Policy | MM Interiors',
    description: 'Refund and cancellation policy for MM Interiors services.',
    h1: 'Refund & Cancellation Policy',
    canonical: `${SITE_URL}/refund-cancellation`,
    noindex: false,
  },
  '/thank-you': {
    title: 'Thank You | MM Interiors',
    description: 'Thank you for contacting MM Interiors. We will get back to you shortly.',
    h1: 'Thank You',
    canonical: `${SITE_URL}/thank-you`,
    noindex: true,
  },
};

/**
 * Get SEO data for a given path.
 * Falls back to a sensible default for 404 / unknown routes.
 */
export function getSeoData(pathname) {
  if (seoData[pathname]) {
    return {
      ...seoData[pathname],
      ogTitle: seoData[pathname].ogTitle || seoData[pathname].title,
      ogDescription: seoData[pathname].ogDescription || seoData[pathname].description,
      ogImage: seoData[pathname].ogImage || DEFAULT_OG_IMAGE,
      siteName: SITE_NAME,
      siteUrl: SITE_URL,
    };
  }

  // 404 fallback
  return {
    title: 'Page Not Found | MM Interiors',
    description: 'The page you are looking for does not exist. Browse our interior design services, projects and contact us for a free consultation.',
    h1: 'Page Not Found',
    canonical: `${SITE_URL}/404`,
    noindex: true,
    ogTitle: 'Page Not Found | MM Interiors',
    ogDescription: 'The page you are looking for does not exist.',
    ogImage: DEFAULT_OG_IMAGE,
    siteName: SITE_NAME,
    siteUrl: SITE_URL,
  };
}

export { SITE_URL, SITE_NAME, DEFAULT_OG_IMAGE };
